name: Deploy TinyURL Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install

      - name: Build project
        run: npm run build

      - name: Verify build
        run: ls -lah dist

      - name: Zip Lambda
        run: zip -j lambda.zip dist/handler.js

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1

      - name: Verify AWS
        run: aws sts get-caller-identity

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
          --function-name tinyurl-service \
          --zip-file fileb://lambda.zip \
          --region eu-west-1